services:
  - type: web
    name: taita-api
    runtime: node
    plan: starter
    buildCommand: |
      npm install && \
      echo "Generating Prisma client..." && \
      npx prisma generate && \
      echo "Running database migrations..." && \
      npx prisma migrate deploy && \
      echo "Seeding database..." && \
      npx prisma db seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: taita-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://taita.blog
      - key: CMS_URL
        value: https://taita.blog
      - key: TENANT_DOMAIN
        value: taita.blog
      - key: UPLOADS_DIR
        value: /app/uploads

databases:
  - name: taita-db
    plan: starter
    databaseName: taita
    user: taita
